### ISSUE TITLE
M1 Mac - Not supported

### ISSUE THREAD

**Issue by Smponi** [Smponi/Paper2Anki#5]
The required package **pymupdf** does not run on the m1 macs. (Well, it can be run but it's a hustle to set it up.)
Therefore I'm planing to replace this package.

**Comment by sjsivert** [comment]
Fantastic!

**Comment by Smponi** [comment]
After ages I found time to look further into it. It seems the broken package already figured it out.
Therefore I tested it with an macbook pro and can confirm it runs as described in the README.md.

If someone else can confirm this works now on apple silicon macs, I will merge this to the master brnach.

**A current pip version is necessary. It worked for me with pip 22.3.1**
